general.auto
general.off
general.raw
product.number
product.name
product.category
product.description
product.price
product.gtin
product.manufacturer
product.manufacturer_number
product.modifier
product.object
product.stock
product.supplier
product.supplier_number
product.rating
product.state
order.frequency